= Example Applications of the Buckingham–Pi Theorem

This repository collects a variety of worked examples from the literature, demonstrating how to apply the Buckingham–Pi theorem in Python.

== Examples

*From BuckinghamPy*  

– Examples from Saad et al. (2021) https://www.sciencedirect.com/science/article/pii/S2352711021001291[BuckinghamPy: A Python software for dimensional analysis]  

  * https://github.com/saadgroup/BuckinghamPy/blob/master/examples.ipynb[examples.ipynb]  

  * Centrifugal Pump example in the README: https://github.com/saadgroup/BuckinghamPy/blob/master/README.md[Centrifugal Pump]

*Hydrogen Knudsen Compressor*  

– From Xie & Qian (2023) https://www.sciencedirect.com/science/article/abs/pii/S0360319923023030[Dimensional-Analysis of hydrogen Knudsen compressor]  

  * https://github.com/xqb-python/Dimensional-Analysis[Dimensional-Analysis repository]  

  * See their script: https://github.com/xqb-python/Dimensional-Analysis/blob/main/%E4%B8%AD%E5%BF%83%E5%9E%82%E7%9B%B4%E7%BA%BF%E4%B8%8A%E7%9A%84%E9%80%9F%E5%BA%A6%E5%88%86%E5%B8%83/%E6%9C%80%E5%A4%A7%E6%BB%91%E7%A7%BB%E9%80%9F%E5%BA%A6.py[Hydrogen Knudsen Compressor Code]

*Optimierung von Stahlgießprozessen*  

– From Lichtenberg (2021) “Optimierung von Stahlgießprozessen anhand eines Wassermodells mit begleitender Strömungssimulation”  

  * https://repo.bibliothek.uni-halle.de/handle/1981185920/87855[Dissertation repository]

== Python scripts

Three complementary approaches are provided:

* https://github.com/dietmarwo/BuckinghamExamples/blob/master/apply_buckinghampy.py[apply_buckinghampy.py]  
  Uses https://github.com/saadgroup/BuckinghamPy[BuckinghamPy] to enumerate all valid π-groups.

* https://github.com/dietmarwo/BuckinghamExamples/blob/master/rank_pi_groups.py[rank_pi_groups.py]  
  Uses NumPy and scikit-learn to  
  1. find all repeating-variable sets,  
  2. compute their π-groups,  
  3. score each set by the predictive R² adding a penalty for bad coefficient-of-variation over your experimental range.

* https://github.com/dietmarwo/BuckinghamExamples/blob/master/optimize_pi_groups.py[optimize_pi_groups.py]  
  1. Uses https://github.com/dietmarwo/fast-cma-es[fcmaes] to apply the https://github.com/avaneev/biteopt[biteopt] evolutionary
  algorithm to vary the pi group exponents, allowing continuous values.   
  2. score each set of pi group exponents by the predictive R² adding a penalty for bad coefficient-of-variation over your experimental range.

=== Customization

1. **Add your own examples** to the `examples` dict (variable names + dimension matrix).    
2. **Plug in your real data** (in place of the random sampling) to get π-group rankings tailored to your experiment.

== Further comparison

Compare the Knudsen-compressor code with:  
https://github.com/xqb-python/Dimensional-Analysis/blob/main/%E4%B8%AD%E5%BF%83%E5%9E%82%E7%9B%B4%E7%BA%BF%E4%B8%8A%E7%9A%84%E9%80%9F%E5%BA%A6%E5%88%86%E5%B8%83/%E6%9C%80%E5%A4%A7%E6%BB%91%E7%A7%BB%E9%80%9F%E5%BA%A6.py[Hydrogen Knudsen Compressor Code], which uses genetic optimization. GA doesn't work well for this application, specially if you allow continuous exponents. Consider evolutionary algorithms like https://github.com/avaneev/biteopt[biteopt] instead. 

=== Citing

[source]
----
@misc{buckpiexams2025,
  author       = {Dietmar Wolz},
  title        = {Example Applications of the Buckingham–Pi Theorem},
  year         = {2025},
  publisher    = {GitHub},
  journal      = {GitHub repository},
  howpublished = {Available at \url{https://github.com/dietmarwo/BuckinghamExamples}},
}










